[colors.primary]
background = "#06061a"
foreground = "#c1c1c5"

[colors.cursor]
text = "#06061a"
cursor = "#c1c1c5"

[colors.vi_mode_cursor]
text = "#06061a"
cursor = "#c1c1c5"

[colors.search.matches]
foreground = "#06061a"
background = "#c1c1c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#454580"
background = "#8d8d98"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#06061a"
red = "#c4705d"
green = "#b25a73"
yellow = "#5fab62"
blue = "#51a0b4"
magenta = "#b29d60"
cyan = "#b78067"
white = "#8d8d98"

[colors.bright]
black = "#454580"
red = "#f6a18d"
green = "#dc8ba2"
yellow = "#90d494"
blue = "#7ecce0"
magenta = "#ddc992"
cyan = "#e3b29c"
white = "#c1c1c5"

[colors.dim]
black = "#c1c1c5"
red = "#f6a18d"
green = "#ddc992"
yellow = "#90d494"
blue = "#7ecce0"
magenta = "#dc8ba2"
cyan = "#e3b29c"
white = "#454580"

