[colors]
background = '#06061a8e'
black = '#06061a'
blue = '#c4705d'
cursor = '#c1c1c5'
cyan = '#b25a73'
foreground = '#c1c1c5'
green = '#5fab62'
magenta = '#51a0b4'
red = '#b29d60'
tabs = '#c1c1c5'
tabs-active = '#b78067'
white = '#c1c1c5'
yellow = '#8d8d98'
dim-black = '#06061a8e'
dim-blue = '#c4705d8e'
dim-cyan = '#b25a738e'
dim-foreground = '#c1c1c58e'
dim-green = '#5fab628e'
dim-magenta = '#51a0b48e'
dim-red = '#b29d608e'
dim-white = '#b780678e'
dim-yellow = '#8d8d988e'
light-black = '#f6a18d'
light-blue = '#dc8ba2'
light-cyan = '#90d494'
light-foreground = '#7ecce0'
light-green = '#ddc992'
light-magenta = '#e3b29c'
light-red = '#c1c1c5'
light-white = '#f6a18d'
light-yellow = '#dc8ba2'
